apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel-app
type: Opaque
stringData:
  # Database credentials
  MYSQL_DATABASE: "{{ mysql_database }}"
  MYSQL_USER: "{{ mysql_user }}"
  MYSQL_PASSWORD: "{{ mysql_password }}"
  MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
  APP_KEY: "{{ app_key }}"