apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-app
  labels:
    app: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  sessionAffinity: ClientIP
